import type { Metadata } from "next";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/components/provider/theme-provider";

export const metadata: Metadata = {
  title: "Discord",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
        <body className="min-h-screen bg-background font-sans text-foreground antialiased">
          <ClerkProvider>
            <ThemeProvider
              attribute="class"
              // defaultTheme="dark"
              enableSystem={true}
              storageKey="discord-clone-theme"
            >
              <div className="h-full">
                {children}
              </div>
            </ThemeProvider>
          </ClerkProvider>
        </body>
    </html>
  );
}
