import type { Metadata } from "next";
import { Open_Sans } from "next/font/google";
import "./globals.css";
import { ClerkProvider } from "@clerk/nextjs";
import { ThemeProvider } from "@/components/provider/theme-provider";
import { ModelProvider } from "@/components/provider/model-provider";

const openSans = Open_Sans({
  variable: "--font-open-sans",
  subsets: ["latin"],
});

const openSansMono = Open_Sans({
  variable: "--font-open-sans-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Discord",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
        <body className="cn(
          font.className,
          bg-white dark:bg-[#313338]
        )">
          <ClerkProvider>
            <ThemeProvider
              attribute="class"
              // defaultTheme="dark"
              enableSystem={true}
              storageKey="discord-clone-theme"
            >
              <div className={`${openSans.variable} ${openSansMono.variable} antialiased h-full`}>
                <ModelProvider />
                {children}
              </div>
            </ThemeProvider>
          </ClerkProvider>
        </body>
    </html>
  );
}
